'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '../../supabase';
import {readAdminSession} from '../../lib/safety.mjs';
import s from '../../learning/Learning.module.css';
const matchLabel={well:'잘 반영됨',partly:'일부 반영됨',different:'많이 다름'};
export default function LearningAdmin(){
 const router=useRouter(),request=useRef(0),lock=useRef(false);
 const [classNo,setClassNo]=useState(1),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const id=++request.current;setBusy(true);setError('');setData(null);try{const session=await readAdminSession(supabase);if(!session){router.replace('/admin/login');return;}const {data,error}=await supabase.rpc('get_learning_admin_v1',{p_class_no:Number(classNo)});if(error)throw error;if(id===request.current)setData(data);}catch{if(id===request.current)setError('학습 기록을 불러오지 못했습니다. 관리자 권한, SQL 06 설치, 연결을 확인해 주세요.');}finally{if(id===request.current)setBusy(false);}}
 useEffect(()=>{load();return()=>{++request.current;};},[classNo]);
 useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT'){++request.current;setData(null);router.replace('/admin/login');}});return()=>subscription.unsubscribe();},[]);
 async function mutate(name,args){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const {error}=await supabase.rpc(name,args);if(error)throw error;await load();}catch{setError('변경을 확인하지 못했습니다. 새로고침 후 현재 상태를 확인해 주세요.');}finally{lock.current=false;setBusy(false);}}
 return <main className={s.wrap}><nav><Link href="/admin">← 작품 승인 관리</Link></nav><section className={s.panel}><span className={s.eyebrow}>LEARNING JOURNEY</span><h1>생각 기록 · 감상 글 확인</h1><p>처음 답변과 마지막 성찰을 함께 살펴보세요. 답변 길이·질문 횟수·반응 수로 점수를 매기지 않습니다.</p><label>반 선택<select disabled={busy} value={classNo} onChange={e=>setClassNo(Number(e.target.value))}>{Array.from({length:10},(_,i)=><option value={i+1} key={i+1}>{i+1}반</option>)}</select></label><button disabled={busy} onClick={load}>새로고침</button>{error&&<p role="alert" className={s.error}>{error}</p>}{busy&&<p role="status">확인 중…</p>}</section>
 {data&&<><section className={s.panel}><h2>학생의 생각과 변화</h2>{!data.records.length&&<p>아직 저장된 생각 기록이 없습니다.</p>}{data.records.map(r=><details key={r.student_no}><summary>{r.student_no}번 · {r.artwork_id?'작품 제출됨':'작성 중'} · 공개 요약 {r.public_approved?'승인':'미승인'}</summary><div className={s.grid}><div><h3>처음 답변</h3><blockquote>{r.payload.turns?.[0]?.answer||'직접 정리한 기록'}</blockquote></div><div><h3>변환 후 판단</h3><p>{matchLabel[r.payload.reflection?.match]}</p><blockquote>{r.payload.reflection?.evidence}</blockquote><p>다음 요청: {r.payload.reflection?.next}</p></div></div><details><summary>전체 질문과 답변 (비공개)</summary>{r.payload.turns?.map((t,i)=><div className={s.turn} key={i}><strong>{t.question}</strong><p>{t.answer}</p></div>)}</details><h3>학생이 확인한 공개 요약</h3><p>의도: {r.payload.summary?.intent}</p><p>유지: {r.payload.summary?.keep}</p><p>변화: {r.payload.summary?.change}</p><p>발견: {r.payload.publicNote}</p><div className={s.actions}><button disabled={busy||!r.artwork_id} onClick={()=>mutate('moderate_learning_v1',{p_class_no:classNo,p_student_no:r.student_no,p_version:r.version,p_approved:!r.public_approved})}>{r.public_approved?'공개 요약 숨기기':'공개 요약 승인'}</button><Link className={s.button} href={`/class/${classNo}/student/${r.student_no}`}>작품 보기</Link><button className={s.secondary} disabled={busy} onClick={()=>{if(window.confirm(`${classNo}반 ${r.student_no}번의 AI 요청 횟수를 초기화할까요? 추가 생성 시 비용이 발생할 수 있습니다.`))mutate('reset_museum_ai_v1',{p_class_no:classNo,p_student_no:r.student_no});}}>AI 횟수 초기화</button></div><p className={s.note}>요약을 승인해도 작품 자체가 승인되어야 공개됩니다. 교사가 작품을 수정했다면 요약 내용도 다시 확인해 주세요.</p><details><summary>수업 돌아보기 (비공개)</summary><p>관찰: {r.payload.survey?.observe||'미응답'} / 판단: {r.payload.survey?.judge||'미응답'}</p><p>친구의 감상에서 발견: {r.payload.survey?.peer}</p><p>어려웠던 점: {r.payload.survey?.difficulty}</p></details></details>)}</section>
 <section className={s.panel}><h2>작가에게 전달할 감상 글</h2><p>승인한 글만 작품을 만든 학생이 접속코드로 열어 봅니다.</p>{!data.feedback.length&&<p>아직 도착한 감상 글이 없습니다.</p>}{data.feedback.map(f=><article key={f.id} className={s.turn}><strong>{f.to_class}반 {f.to_student}번에게</strong><p className={s.note}>작성: {f.from_class}반 {f.from_student}번 · {({pending:'승인 대기',approved:'전달 승인',hidden:'숨김'})[f.status]}</p><blockquote>{f.body}</blockquote><div className={s.actions}><button disabled={busy||f.status==='approved'} onClick={()=>mutate('moderate_feedback_v1',{p_id:f.id,p_body:f.body,p_status:'approved'})}>전달 승인</button><button className={s.secondary} disabled={busy||f.status==='hidden'} onClick={()=>mutate('moderate_feedback_v1',{p_id:f.id,p_body:f.body,p_status:'hidden'})}>숨기기</button></div></article>)}</section></>}
 </main>;
}
