'use client';
import {useState,useRef} from 'react';
import {supabase} from '../supabase';
import s from './Learning.module.css';
export default function Inbox({classNo,studentNo}){
 const [code,setCode]=useState(''),[items,setItems]=useState(null),[survey,setSurvey]=useState({observe:'',judge:'',peer:'',difficulty:''}),[hasRecord,setHasRecord]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const lock=useRef(false);
 const auth={p_class_no:classNo,p_student_no:studentNo,p_access_code:code.trim()};
 async function load(){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{const results=await Promise.all([supabase.rpc('get_my_feedback_v1',auth),supabase.rpc('get_my_learning_v1',auth)]);if(results.some(r=>r.error))throw new Error();setItems(results[0].data);setHasRecord(!!results[1].data.payload);setSurvey(results[1].data.payload?.survey||{observe:'',judge:'',peer:'',difficulty:''});}catch{setItems(null);setMessage('반·번호에 맞는 접속코드와 연결을 확인해 주세요.');}finally{setBusy(false);lock.current=false;}}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);try{const {error}=await supabase.rpc('save_learning_survey_v1',{...auth,p_survey:survey});if(error)throw error;setMessage('나의 돌아보기를 저장했어요. 나와 선생님만 볼 수 있습니다.');}catch{setMessage('저장하지 못했습니다. 다시 시도해 주세요.');}finally{setBusy(false);lock.current=false;}}
 return <section className={s.panel}><h2>나에게 도착한 감상 · 수업 돌아보기</h2>{items===null?<><label>작품을 만든 학생의 접속코드<input type="password" value={code} autoComplete="off" onChange={e=>setCode(e.target.value)} /></label><button type="button" disabled={busy||!code.trim()} onClick={load}>내 감상 편지 열기</button></>:<><button type="button" className={s.secondary} onClick={()=>{setCode('');setItems(null);setSurvey({observe:'',judge:'',peer:'',difficulty:''});}}>닫고 접속코드 지우기</button>{items.length?items.map(item=><blockquote key={item.id}>{item.body}</blockquote>):<p>아직 선생님의 확인을 마친 감상 글이 없어요.</p>}{hasRecord&&<div className={s.survey}><h3>처음 생각과 지금 생각 비교하기</h3>{[['observe','원작의 색·선·질감을 전보다 구체적으로 설명할 수 있나요?'],['judge','AI 결과에서 내 의도와 다른 부분을 찾을 수 있나요?']].map(([k,q])=><label key={k}>{q}<select value={survey[k]||''} onChange={e=>setSurvey({...survey,[k]:e.target.value})}><option value="">선택</option><option value="yes">그렇다</option><option value="some">조금 그렇다</option><option value="notyet">아직 어렵다</option></select></label>)}<label>친구의 감상으로 새롭게 발견한 것이 있나요?<textarea value={survey.peer||''} maxLength={500} onChange={e=>setSurvey({...survey,peer:e.target.value})}/></label><label>어느 과정이 어렵거나 도움이 되지 않았나요?<textarea value={survey.difficulty||''} maxLength={500} onChange={e=>setSurvey({...survey,difficulty:e.target.value})}/></label><button type="button" disabled={busy} onClick={save}>돌아보기 저장</button></div>}</>}<p role="status">{busy?'확인 중…':message}</p></section>;
}
